# 编码者的配置
llm_model: "deepseek-v4-pro" # 目前支持deepseek
api_key: "sk-8f026b1a113b4c428f0b1e58eb1e7eee"
reasoning_effort: "high"
max_iteration: 50 # 同一个问题最大步数
max_retry: 3 # 同一个工具连续调用失败3次直接回报
timeout: 630 # 工具执行的最长等待时间（秒） 