# 通用工具的配置文件

# 文件操作
file_operation:
  read_file:
    size_limit: 5MB # 直接读取文件的大小限制，可以写B,KB,MB,GB

# 运行命令
system_command:
  run_python:
    output_limit: 100KB # 读取控制台返回的大小限制，可以写B,KB,MB,GB
    timeout: 600 # 运行超时时间，可以写xx秒。一次运行不建议太久，大任务应采用并行、多次运行的设计。